# pcall

保護されたモードで関数を呼び出す（エラーが発生しても処理を継続させる）

```lua
pcall (f, arg1, ···)
```

## 説明

関数`f`を保護モードで与えられた引数で呼び出します。これは、`f`内の任意のエラーが伝播されないことを意味します。代わりに、`pcall`はエラーをキャッチし、ステータスコードを返します。最初の結果はステータスコード（真偽値）であり、エラーなしに呼び出しが成功すると`true`になります。その場合、`pcall`はこの最初の結果の後に、呼び出しからの全ての結果を返します。エラーが発生した場合、`pcall`は`false`とエラーメッセージを返します。

## サンプルコード

```lua
local status, err = pcall(function() error("error") end)
print(status, err)
```

この例では、エラーが発生してもプログラムが停止せず、エラーメッセージが表示されます。

## 互換性

- Lua5.1

## 関連項目

- [`xpcall`](xpcall.md)